### ISSUE TITLE
Feat: QR코드 클라이언트에서 생성하기

### ISSUE THREAD

**Issue by kdh8219** [sunwoo1524/krll#1]
현재 동작이, 외부 웹사이트에서 끌어다 쓰고있는데, 스타일이 고정인점과 프라이버시가 문제가 되고있습니다.
따라서 QR을 클라이언트에서 생성하면 좋을 것 같습니다.

**Comment by sunwoo1524** [comment]
괜찮은 것 같아요
추가하겠습니다

**Comment by sunwoo1524** [comment]
반영했습니다!
https://github.com/sunwoo1524/krll/releases/tag/v0.0.5

**Comment by kdh8219** [comment]
c56e7c75f401359c605d2853245f93a4a214b6cd
