### ISSUE TITLE
Bug: QRCode.js 미작동

### ISSUE THREAD

**Issue by kdh8219** [sunwoo1524/krll#4]
![Screenshot_20241019_145201_Firefox](https://github.com/user-attachments/assets/7633cb8e-af3f-4aa9-b210-4b69941ca648)
Firefox android 130.0.1 (Build #2016044751)
확장 프로그램 없음

**Comment by sunwoo1524** [comment]
131.0.3(구글 플레이 스토어 기준 최신 버전) 기준으로 작동합니다. 브라우저를 최신 버전으로 업데이트해보세요.

**Comment by kdh8219** [comment]
![Screenshot_20241019_150857_Firefox](https://github.com/user-attachments/assets/9ae4bd73-6ffd-43be-a137-e62e701151fd)
Firefox Android 131.0.3 (Build #2016050031)
확장프로그램 확실히 끄려고 사생활 보호 모드 가서 해봤어요

**Comment by sunwoo1524** [comment]
다른 브라우저로 테스트 해보시겠어요? 브라우저 문제인지 확인이 필요합니다

**Comment by kdh8219** [comment]
![Screenshot_20241019_153009_Chrome](https://github.com/user-attachments/assets/1aef9ac0-876f-4ef6-baa1-4c59a8d83f66)
방금 설치한 따끈따끈한
Android Chrome 129.0.6668.102
브라우저 문제 아닌가보네요

**Comment by kdh8219** [comment]
![Screenshot_20241019_153225_Firefox](https://github.com/user-attachments/assets/039f857b-ff79-4ae1-bc0b-bc6fea3b0d1c)
cloudflare 접속문제는 아니네요

**Comment by sunwoo1524** [comment]
브라우저 문제도 아니고 qrcode.js 로드도 잘 하면 왜 안되는지 더 감이 안 잡히네요.
이슈 열어두고 왜 문제가 발생하는지 계속 알아보겠습니다.
조금만 기다려주세요. 죄송합니다.

**Comment by kdh8219** [comment]
시도해본거:
- vpn을 변경해봄: 실패
- vpn을 끄고 kt 통피로 접속해봄: 실패
- dns를 cloudflare로 변경해봄: 실패

**Comment by kdh8219** [comment]
지금 보니 작동하네요
도대체 뭐가 변수인지 모르겠어요

**Comment by sunwoo1524** [comment]
오늘 링크를 두번 이상 단축하면 QR 코드가 계속 쌓이는 버그 패치한 업데이트를 적용했는데 그게 해결해준 걸 수도 있겠네요. 어떻게 해결된건지는 모르겠지만 아무튼 다행입니다!

**Comment by kdh8219** [comment]
> 오늘 링크를 두번 이상 단축하면 QR 코드가 계속 쌓이는 버그 패치한 업데이트를 적용했는데 그게 해결해준 걸 수도 있겠네요. 어떻게 해결된건지는 모르겠지만 아무튼 다행입니다!

사실 2일전부터 되는건 확인했었어요
